version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=582200
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpresspwd
    volumes:
      - ./template/mysqlDB:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wordpress
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpresspwd
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./template/wordpress:/var/www/html

